:- module(training_data, [case/4]).

case([apache,data],[software,devops,database,mobile,data,cloud,streaming,apache,architecture],[],data_analytics).
case([it,data],[software,devops,database,mobile,data,cloud,scraping,server],[scraping],data_analytics).
case([rest,apis],[software,devops,database,mobile,data,cloud,rest,apis,tutorial],[rest,it],web_development).
case([rest,apis],[],[rest,apis],web_development).
case([chatbot],[software,devops,database,mobile,data,cloud,chatbot],[chatbot],ia).
case([enterprise,integration],[software,devops,database,mobile,data,cloud,integration,processing],[enterprise,integration],integration).
case([linux,container,real-time],[software,devops,database,mobile,data,cloud,linux,container,docker],['i/o',linux,cpu,can],devops).
case([kotlin],[software,devops,database,mobile,data,cloud,tutorial,kotlin],[kotlin],devops).
case([kubernetes,architecture,devops],[software,devops,database,mobile,data,cloud,kubernetes,tutorial],[set,kubernetes],devops).
case([debugging,angular],[software,devops,database,mobile,data,cloud,angular],[debugging,default,angular],web_development).
case([testing,ai],[software,devops,database,mobile,data,cloud,testing],[testing],ia).
case([testers],[software,devops,database,mobile,data,cloud,testing,testers],[testers],testing).
case([drive,kubernetes,gitops,devops],[software,devops,database,mobile,data,cloud,kubernetes,tutorial,gitops],[cd,gitops],devops).
case([securing],[software,devops,database,mobile,data,cloud,spring,security,tutorial],[spring,security],security).
case([archlinux,tutorial,basic],[software,devops,database,mobile,data,cloud,linux,archlinux,iso],[developer,tutorial,install,platform,archlinux],so).
case([crud,app,kotlin,spring,boot],[software,devops,database,mobile,data,cloud,kotlin,spring,boot,javascript,tutorial,crud,application],[tutorial,crud,application,kotlin,spring,boot],web_development).
case([alexa,python,ai],[software,devops,database,mobile,data,cloud,alexa,python,aws,lambda],[alexa,python,npm,aws,lambda],ia).
case([edr,security],[software,devops,database,mobile,data,cloud,edr,security],[endpoint],security).
case([api,security],[software,devops,database,mobile,data,cloud,api,apis,security,integration],[api,vulnerabilities,wordpress],security).
case([api,security],[software,devops,database,mobile,data,cloud,api,apis,security],[security,app,api],security).
case([cybersecurity,security],[software,devops,database,mobile,data,cloud,security],[cybersecurity],security).
case([penetration,api,security],[software,devops,database,mobile,data,cloud,api,penetration,testing,security,rest],[penetration,testing,rest,api,security,method],security).
case([secure,security],[software,devops,database,mobile,data,cloud,security,application,testing],[security],security).
case([mule,client,integration],[software,devops,database,mobile,data,cloud,mule,api,security,client],[client,mule,application,api],integration).
case([api,integration],[software,devops,database,mobile,data,cloud,integration,architecture,api],[application,integration,apis],integration).
case([digital,integration],[software,devops,database,mobile,data,cloud,mulesoft,api,integration],[can,mulesoft,it],integration).
case([spring,beans],[software,devops,database,mobile,data,cloud,spring,tutorial,beans],[spring,beans],programming).
case([apache,kafka,data],[software,devops,database,mobile,data,cloud,apache,kafka,cluster],[kafka],data_analytics).
case([data,database],[software,devops,database,mobile,data,cloud],[database,data],database).
case([kubernetes],[software,devops,database,mobile,data,cloud,security,scalable],[],devops).
case([],[software,devops,database,mobile,data,cloud,'c++',array,tutorial],['c++'],programming).
case([data],[software,devops,database,mobile,data,cloud,application,architecture],[applications,app,architecture,devops],devops).
case([resttemplate,webclient,java],[software,devops,java,database,mobile,data,cloud,resttemplate,webclient,api,spring,boot,client],[spring,client,resttemplate,webclient],web_development).
case([cobol,it],[software,devops,java,database,mobile,data,cloud,cobol,mainframe],[developer,cobol],programming).
case([web,components],[software,devops,java,web,database,mobile,data,cloud,components,javascript,app,mvc,interface],[web,components,ui,application],web_development).
case([tutorial,firebase,hosting,web],[software,devops,java,web,database,mobile,data,cloud,firebase,applications,tutorial,hosting],[hosting,application,firebase],web_development).
case([css,flexbox,web],[software,devops,java,web,database,mobile,data,cloud,css,flexbox],[css,flexbox],web_development).
case(['node.js',tutorial],[],[laptop,'node.js','back-end',tutorial,smartphone],web_development).
case([hooks,typescript,tutorial],[],[hooks,can],web_development).
case([model],[],[models],ia).
case([ai,machine,learning],[],[ai,models,can,machine,learning],ia).
case([secure,rest,api,'node.js'],[],[rest,apis,web,developer,platform],web_development).
case([angular,app],[],[application,angular,cli,firebase,'back-end'],web_development).
case([javascript,design,patterns],[],[design,patterns,software,javascript],programming).
case([mobile,web,applications,firebase],[],[firebase,can,it,mobile,web],cloud).
case([golang,go],[],[oop,go,patterns,can,golang],programming).
case([jenkins,java,continuous,integration],[software,devops,java,web,database,mobile,data,cloud,continuous,integration,docker,jenkins],[devops,tutorial,jenkins,continuous,integration,java],devops).
case([platform,data],[software,devops,java,web,database,mobile,data,cloud,grafana],[grafana],data_analytics).
case([aws,integration,cloud],[software,devops,java,web,database,mobile,data,cloud,aws,docker,jenkins,slack],[cpu,set],cloud).
case([testers],[software,devops,java,web,database,mobile,data,cloud,continuous,testers,testing],[testers],testing).
case([blob,database],[software,devops,java,web,database,mobile,data,cloud,blob,memory,tutorial],[],database).
case([domain,model,spring,java],[software,devops,java,web,database,mobile,data,cloud,architecture,mvc,domain,spring],[developer,design,patterns,architecture],sof_engineering).
case([mule,integration],[software,devops,java,web,database,mobile,data,cloud,mule,tutorial,mulesoft],[mule],integration).
case([queue,java],[software,devops,java,web,database,mobile,data,cloud,kotlin,tutorial],[applications,queue],programming).
case([app,chatbot],[],[enterprise,web,app,whatsapp,it,chatbot],mobile).
case([crm,integration],[],[crm,integration],integration).
case([programming,language,'c++'],[],[can,language,'c++'],programming).
case([native,hybrid],[],[native,hybrid,mobile],mobile).
case([image,classification,data],[],[learning,computer,deep,access],ia).
case([text,editors,programming],[],[tutorial,text,editors,'node.js',server,vscode],programming).
case([bayesian,inference],[],[bayesian,inference,can],ia).
case([sql,server],[],[microsoft,sql,server,oracle],database).
case([rendering,path,website],[],[rendering,bounce,it,path,website],web_development).
case([oracle,database],[programming,software,devops,java,web,database,mobile,data,cloud,docker,oracle],[oracle,database],database).
case([performance,testing,stress],[programming,software,devops,java,web,database,mobile,data,cloud,testing,performance,stress],[testing],testing).
case([devops],[programming,software,devops,java,web,database,mobile,data,cloud],[software,process],devops).
case([apache,spark,storm,data],[programming,software,devops,java,web,database,mobile,data,cloud,apache,spark,storm,streaming],[apache,storm,spark],data_analytics).
case([data,extraction,tables],[programming,software,devops,java,web,database,mobile,data,cloud,extraction,table],[data,tables],data_analytics).
case([applications,artificial,intelligence,ai],[programming,software,devops,java,web,database,mobile,data,cloud,ai,applications,artificial,intelligence,machine,learning],[applications,ai],ia).
case([convolutional,neural,network,ai],[programming,software,devops,java,web,database,mobile,data,cloud,ai,machine,python,tutorial],[data,it,back],ia).
case([artificial,intelligence,ai],[programming,software,devops,java,web,database,mobile,data,cloud,artificial,chatbot,computing,machine,learning,ai,language,processing],[artificial,intelligence],ia).
case([ai],[programming,software,devops,java,web,database,mobile,data,cloud,developer],[developer,ai],ia).
case([robotic,ai],[programming,software,devops,java,web,database,mobile,data,cloud,ai,deep,learning,ios,machine,siri],[apple,ai],ia).
case([serverless,azure,cloud],[programming,software,devops,java,web,database,mobile,data,cloud,azure,serverless],[serverless,azure],cloud).
case([spring,boot,app,docker,cloud],[programming,software,devops,java,web,database,mobile,data,cloud,docker,spring,boot],[spring,boot,docker],cloud).
case([iot],[programming,software,devops,java,web,iot,database,mobile,data,cloud,internet,javascript,node,nodejs,security],['node.js',iot],iot).
case([microsoft,programming,language,bosque,sd],[],[software],programming).
case([sd,deno],[],[software],programming).
case([sd,apache,spark,cloud],[],[software],cloud).
case([sync,data,sd],[],[software],data_analytics).
case([webassembly],[webassembly,security,development,architecture,design,software],[webassembly,security],security).
case([amazon,ultrawarm,elastic,search,service,aws],[aws,ultrawarm,development,devops,ai,data,cloud,amazon,web,services,search,cache],[amazon,ultrawarm,service],cloud).
case([predicting,tests,machine,learning],[predicting,tests,ai,data,machine,learning,testing,oop],[machine,learning,tests],ia).
case([cloud,backup],[cloud,development,architecture,design,devops,ai,data,nosql,platform],[blog,post,cloud,service],cloud).
case([amazon,streaming,aws,glue],[aws,glue,streaming,development,architecture,design,devops,ai,data,cloud,amazon],[amazon,aws,glue,streaming,set,continuous,data,it],cloud).
case([],[ai,data,learning,deep],[learning],ia).
case([mozilla,cloud],[mozilla,cloud,ai,data],[cloud,mozilla],cloud).
case([encryption,native,browser],[encryption,native,browser,development,javascript,web,mobile,webassembly,cryptography,security],[surface,encryption,browser,it,native],security).
case([javascript,web,development],[javascript,web,development,architecture,design,html5,typescript,internet,css,html,testing,language,mobile],[javascript,web,development],web_development).
case([javascript,web,development],[javascript,web,development,architecture,design,html5,typescript,internet,css,html,mobile],[javascript,html,css,web,development],web_development).
case([],[iot,development,artificial,intelligence,mobile],[internet,artificial,intelligence],ia).
case([spring,boot,microservices,java],[programming,software,development,devops,java,web,iot,database,mobile,data,cloud,spring,boot],[spring,boot,microservices],integration).
case([internet,things,iot],[programming,software,development,devops,java,web,iot,database,mobile,data,cloud],[internet,things,applications],iot).
case([iot,machine,learning],[programming,software,development,devops,java,web,iot,database,mobile,data,cloud,intelligence,internet,things,machine,learning],[machine,learning],ia).
case([edge,computer,hardware,design,iot],[programming,software,development,devops,java,web,iot,database,mobile,data,cloud,edge,architecture,computing,things,kubernetes],[edge,computer,hardware],hardware).
case([mobile,devops],[programming,software,development,devops,java,web,iot,database,mobile,data,cloud,android,app,continuous,integration,process,ios],[mobile,application,development,devops,web],devops).
case([continuous,travis,ci,'sentry.io',devops],[programming,software,development,devops,java,web,iot,database,mobile,data,cloud,integration,travis,ci,tutorial],[continuous,travis,ci,'sentry.io'],devops).
case([oauth,tokens,security],[programming,software,development,devops,java,web,iot,database,mobile,data,cloud,oauth,access,token,security,spring,tutorial],[basic,server,tokens,username],security).
case([apache,client,big,data],[programming,software,development,devops,java,web,iot,database,mobile,big,data,cloud,apache,ignite,computing],[client,apache,ignite],data_analytics).
case([cloud,services],[programming,software,development,devops,java,web,iot,database,mobile,big,data,cloud,saas],[application,architecture],cloud).
case([spring,data,java],[programming,software,development,devops,java,web,iot,database,mobile,big,data,cloud,microservices,oauth,spring,boot,security],[model,spring,data],programming).
case([sql,database],[programming,software,development,devops,java,web,iot,database,mobile,big,data,cloud,backup,models,sql,server],[sql,server,set,database],database).
case([sql,database],[programming,software,development,devops,java,web,iot,database,mobile,big,data,cloud,sql,tutorial],[drag,data,back,sql],database).
case([mariadb,database],[programming,software,development,devops,java,web,iot,database,mobile,big,data,cloud,kubernetes,mariadb,'real-time',tutorial],[],database).
case([upload,spring,boot,angular,mysql,database],[programming,software,development,devops,java,web,iot,database,mobile,big,data,cloud,angular,spring,boot,'2.0',upload],[image,angular,ui,it,spring,backend],database).
case([couchbase,query,database],[programming,software,development,devops,java,web,iot,database,mobile,big,data,cloud,couchbase,query,nosql,tutorial],[query,services,performance],database).
case([microservices],[programming,software,development,devops,java,web,iot,database,mobile,big,data,cloud],[microservices],integration).
case([application,performance],[programming,software,development,devops,java,web,iot,database,mobile,big,data,cloud,performance,management,testing],[application,performance],testing).
case([iot,security,secure],[programming,software,development,devops,java,web,iot,database,mobile,big,data,cloud,security,network,smart],[iot,security],security).
case([leds,push,buttons,iot],[programming,software,development,devops,java,web,iot,database,mobile,big,data,cloud],[post,gpio,leds],iot).
case([go,visitor,pattern,web],[programming,software,development,devops,java,web,iot,database,mobile,big,data,cloud,go,tutorial,visitor,design,pattern],[visitor,pattern,go],web_development).
case(['.net',application,development,web],[programming,software,development,devops,java,web,iot,database,mobile,big,data,cloud,application,asp,'.net','asp.net',session],[developers,'.net'],web_development).
case([design,patterns,template,pattern,web],[programming,software,development,devops,java,web,iot,database,mobile,big,data,cloud,design,patterns,template,pattern],[template,design,pattern],web_development).
case(['real-time',analytics,web],[programming,software,development,devops,java,web,iot,database,mobile,big,data,cloud,javascript,nlp,'real-time',tutorial],['real-time',analytics,application,ring,javascript,sdk],web_development).
case([css,web],[programming,software,development,devops,java,web,iot,database,mobile,big,data,cloud,html,tutorial,model,css],[model,html,css,it],web_development).
case([v8,javascript,web],[programming,software,development,devops,java,web,iot,database,mobile,big,data,cloud,javascript,v8],[v8,engine,javascript],web_development).
case([experts,web],[programming,software,development,devops,java,web,iot,database,mobile,big,data,cloud,angular],[angular],web_development).
case([web,scraping,python],[],[python,javascript],web_development).
case([sql,index,developers],[],[sql,database,index,it,logic,tutorial],database).
case([arduino],[],[php,jquery,arduino,'real-time'],iot).
case([programming,language,'c++'],[],[software,language],programming).
case([image,classification,data],[],[learning,computer,deep,access],ia).
case([react,hooks,data],[],[logic,ui,developers,react,hooks,components,tutorial,http,cache],web_development).
case([encrypted,dns,https],[],[internet,encrypted,server,dns,https,tls],security).
case([webpack,react],[],[webpack,tutorial,go,react,app],web_development).
case(['http/3'],[],['http/3',http,protocol],web_development).
case([ai],[],[ai,machine,learning,models,data],ia).
case([programming,tutorial,'.net'],[],[programming,tutorial,database,management],programming).
case([react,native,deep],[],[react,native,developer],mobile).
case([angular,authentication,'node.js'],[],[json,web,tokens,method,tutorial,software,authentication,angular,application,'node.js'],web_development).
case([apache,cordova,mobile,html,css],[],[mobile,applications,platform],mobile).
case([http,android],[],[http,streaming],mobile).
case([ios,development],[],[ios,development,ruby],mobile).
case([ios,ui,design],[],[ios,ui,design],mobile).
case([android,tutorial],[],[android,debug],mobile).
case([android,developer,xamarin],[],[android,developer,mobile],web_development).
case([java,lombok],[],[java,design,it,programming,language,developers,set],programming).
case([app,development,xamarin],[],[mobile,app,programming,platform,software],mobile).
case([automated,tests,ios],[],[tutorial,automated,testing,ios,platform,it],testing).
case([android,development,kotlin],[],[kotlin,programming,language,machine,jvm,bytecode,it,java,performance,software],mobile).
case([rxjava,android],[],[applications,rxjava,java,reactive,programming,android,it],mobile).
case([android,performance,patterns],[],[android,mobile,app,performance,long],mobile).
case([ethereum,oracle],[],[smart],blockchain).
case([ethereum,solidity,oracle,contracts],[],[solidity,ethereum,smart],blockchain).
case([management,library,react],[react,management,development,javascript,native,web],[management,facebook,applications],web_development).
case([ibm,access,toolkit,developers,applications],[ibm,accessibility,development,interface,web],[ibm,access,toolkit,accessibility,developers,testers,set],testing).
case([apache,lightning,big,data],[apache,java,development,architecture,design,big,data,database],[apache,data,format,it],data_analytics).
case([genetic,algorithms,python],[genetic,algorithms,ai,data,machine,learning],[genetic,algorithms,python],ia).
case([language,platform,application,developers],[cloud,native,programming,ballerina,development,architecture,design,computing],[ballerina,programming,language,cloud,native],programming).
case([data,spring,cloud],[spring,data,patterns,architecture,design,ai,platform,cloud,java,streaming],[patterns,data],cloud).