:- module(training_data, [case/4]).

case([apache,data],[software,devops,database,mobile,data,cloud,streaming,apache,architecture],[],data_analytics).
case([it,data],[software,devops,database,mobile,data,cloud,scraping,server],[scraping],data_analytics).
case([rest,apis],[software,devops,database,mobile,data,cloud,rest,apis,tutorial],[rest,it],web_development).
case([rest,apis],[],[rest,apis],web_development).
case([chatbot],[software,devops,database,mobile,data,cloud,chatbot],[chatbot],ia).
case([enterprise,integration],[software,devops,database,mobile,data,cloud,integration,processing],[enterprise,integration],integration).
case([linux,container,real-time],[software,devops,database,mobile,data,cloud,linux,container,docker],['i/o',linux,cpu,can],devops).
case([kotlin],[software,devops,database,mobile,data,cloud,tutorial,kotlin],[kotlin],devops).
case([kubernetes,architecture,devops],[software,devops,database,mobile,data,cloud,kubernetes,tutorial],[set,kubernetes],devops).
case([debugging,angular],[software,devops,database,mobile,data,cloud,angular],[debugging,default,angular],web_development).
case([testing,ai],[software,devops,database,mobile,data,cloud,testing],[testing],ia).
case([testers],[software,devops,database,mobile,data,cloud,testing,testers],[testers],testing).
case([drive,kubernetes,gitops,devops],[software,devops,database,mobile,data,cloud,kubernetes,tutorial,gitops],[cd,gitops],devops).
case([securing],[software,devops,database,mobile,data,cloud,spring,security,tutorial],[spring,security],security).
case([archlinux,tutorial,basic],[software,devops,database,mobile,data,cloud,linux,archlinux,iso],[developer,tutorial,install,platform,archlinux],so).
case([crud,app,kotlin,spring,boot],[software,devops,database,mobile,data,cloud,kotlin,spring,boot,javascript,tutorial,crud,application],[tutorial,crud,application,kotlin,spring,boot],web_development).
case([alexa,python,ai],[software,devops,database,mobile,data,cloud,alexa,python,aws,lambda],[alexa,python,npm,aws,lambda],ia).
case([edr,security],[software,devops,database,mobile,data,cloud,edr,security],[endpoint],security).
case([api,security],[software,devops,database,mobile,data,cloud,api,apis,security,integration],[api,vulnerabilities,wordpress],security).
case([api,security],[software,devops,database,mobile,data,cloud,api,apis,security],[security,app,api],security).
case([cybersecurity,security],[software,devops,database,mobile,data,cloud,security],[cybersecurity],security).
case([penetration,api,security],[software,devops,database,mobile,data,cloud,api,penetration,testing,security,rest],[penetration,testing,rest,api,security,method],security).
case([secure,security],[software,devops,database,mobile,data,cloud,security,application,testing],[security],security).
case([mule,client,integration],[software,devops,database,mobile,data,cloud,mule,api,security,client],[client,mule,application,api],integration).
case([api,integration],[software,devops,database,mobile,data,cloud,integration,architecture,api],[application,integration,apis],integration).
case([digital,integration],[software,devops,database,mobile,data,cloud,mulesoft,api,integration],[can,mulesoft,it],integration).
case([spring,beans],[software,devops,database,mobile,data,cloud,spring,tutorial,beans],[spring,beans],programming).
case([apache,kafka,data],[software,devops,database,mobile,data,cloud,apache,kafka,cluster],[kafka],data_analytics).
case([data,database],[software,devops,database,mobile,data,cloud],[database,data],database).
case([kubernetes],[software,devops,database,mobile,data,cloud,security,scalable],[],devops).
case([],[software,devops,database,mobile,data,cloud,'c++',array,tutorial],['c++'],programming).
case([data],[software,devops,database,mobile,data,cloud,application,architecture],[applications,app,architecture,devops],devops).
case([resttemplate,webclient,java],[software,devops,java,database,mobile,data,cloud,resttemplate,webclient,api,spring,boot,client],[spring,client,resttemplate,webclient],web_development).
case([cobol,it],[software,devops,java,database,mobile,data,cloud,cobol,mainframe],[developer,cobol],programming).
case([web,components],[software,devops,java,web,database,mobile,data,cloud,components,javascript,app,mvc,interface],[web,components,ui,application],web_development).
case([tutorial,firebase,hosting,web],[software,devops,java,web,database,mobile,data,cloud,firebase,applications,tutorial,hosting],[hosting,application,firebase],web_development).
case([css,flexbox,web],[software,devops,java,web,database,mobile,data,cloud,css,flexbox],[css,flexbox],web_development).
case(['node.js',tutorial],[],[laptop,'node.js','back-end',tutorial,smartphone],web_development).
case([hooks,typescript,tutorial],[],[hooks,can],web_development).
case([model],[],[models],ia).
case([ai,machine,learning],[],[ai,models,can,machine,learning],ia).
case([secure,rest,api,'node.js'],[],[rest,apis,web,developer,platform],web_development).
case([angular,app],[],[application,angular,cli,firebase,'back-end'],web_development).
case([javascript,design,patterns],[],[design,patterns,software,javascript],programming).
case([mobile,web,applications,firebase],[],[firebase,can,it,mobile,web],cloud).
case([golang,go],[],[oop,go,patterns,can,golang],programming).